from setuptools import setup, find_packages

setup(
    name="pdf-qa",
    version="0.1.0",
    description="PDF Question Answering System with Multilingual Support",
    author="AI Team",
    packages=find_packages(),
    python_requires=">=3.8",
    install_requires=[
        'numpy>=1.24.0',
        'pandas>=2.0.0',
        'PyYAML>=6.0.1',
        'torch>=2.0.0',
        'transformers>=4.30.0',
        'sentence-transformers>=2.2.0',
        'scikit-learn>=1.3.0',
        'chromadb>=0.4.0',
        'networkx>=3.0',
        'spacy>=3.8.0',
        'regex>=2022.10.0',
        'langdetect>=1.0.9',
        'PyMuPDF>=1.21.0',
        'fastapi>=0.100.0',
        'uvicorn>=0.20.0',
        'pydantic>=2.0.0',
        'python-multipart>=0.0.5',
        'psutil>=5.9.0',
        'tqdm>=4.65.0',
        'loguru>=0.7.0',
        'python-dotenv>=1.0.0',
        'pathlib>=1.0.1',
        'huggingface-hub>=0.15.0',
        'Pillow>=10.0.0',
    ],
    extras_require={
        'dev': [
            'pytest>=7.0.0',
            'black>=23.3.0',
        ],
    },
    include_package_data=True,
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Intended Audience :: Developers",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
) 